on: push
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Node.js version
        run: node --version

      - name: Check NPM version
        run: npm --version