name: CI/CD Pipeline for Node.js API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Instalar dependencias y ejecutar pruebas automatizadas
  test:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Instalar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Versión de Node.js

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      - name: Grant permission to Jest
        run: chmod +x ./node_modules/.bin/jest

      # Paso 4: Ejecutar pruebas automatizadas
      - name: Run tests
        run: npm test  # Asegúrate de que tienes un script de prueba en tu package.json

# Job 2: Escaneo de vulnerabilidades
  security_scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Instalar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Escanear vulnerabilidades con Snyk
      - name: Snyk vulnerability scan
        uses: snyk/actions/node@v4  # Utiliza la versión etiquetada más reciente
        with:
          args: test --severity-threshold=high  # Escanea solo vulnerabilidades de severidad alta o superior
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Asegúrate de que el token esté correctamente configurado en Secrets

