name: CI/CD Pipeline for Node.js API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
  security-events: write
jobs:
  # Job 1: Instalar dependencias y ejecutar pruebas automatizadas
  test:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Instalar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Versión de Node.js

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      - name: Grant permission to Jest
        run: chmod +x ./node_modules/.bin/jest

      # Paso 4: Ejecutar pruebas automatizadas
      - name: Run tests
        run: npm test  # Asegúrate de que tienes un script de prueba en tu package.json

# Job 2: Escaneo de vulnerabilidades
  security_scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk1.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk1.sarif
  deploy:
      runs-on: ubuntu-latest
      needs: security_scan
      steps:
        # Paso 1: Clonar el código del repositorio
        - name: Checkout code
          uses: actions/checkout@v2

        # Paso 2: Instalar Node.js
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'

        # Paso 3: Instalar dependencias
        - name: Install dependencies
          run: npm install

        # Paso 4: Construir la aplicación (si es necesario)
        - name: Build application
          run: npm run build  # Cambia esto si tienes un proceso de build

        # Paso 5: Instalar Railway CLI
        - name: Install Railway CLI
          run: npm install -g @railway/cli

        - name: Deploy to Railway
          env:
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          run: railway up